# Generated by Django 3.1.1 on 2021-03-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20210312_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='valid_until',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
